In [123]:
import pandas as pd
import ast
import matplotlib.pyplot as plt
from statistics import mode
import json

In [47]:
df_companies = pd.read_csv('C:/Users/Valen/Desktop/TalentPitch/Prueba BI - Data Analyst/t_companies.csv', encoding='utf-8') #Carga de  los datos

In [48]:
df_companies.head()

,description,thematic_areas,features_culture_organization,digital_tools,work_methods,outstanding_knowledge_community,soft_skills,key
0,"Autodesk is a design, engineering, and constru...",NaN,NaN,"[""AutoCAD"", ""Revit"", ""Inventor"", ""Maya"", ""Clou...","[""remote"", ""in_house"", ""mixed""]","[""technology"", ""accounting"", ""customer_service""]","[""problem_solving"", ""teamwork"", ""innovation"", ...",technology
1,Somos una compañía que agrupa soluciones en se...,NaN,NaN,[],NaN,NaN,NaN,services
2,Every company has a mission. What's ours? To e...,NaN,NaN,"[""Microsoft Azure"", ""Microsoft 365"", ""Windows""...","[""remote"", ""in_house"", ""mixed""]","[""marketing_sales"", ""technology"", ""work_method...","[""assertive_communication"", ""teamwork"", ""probl...",technology
3,General Medica de Colombia SA,NaN,NaN,NaN,NaN,NaN,NaN,health
4,McDonalds is an American fast food restaurant ...,NaN,NaN,"[""Webex"", ""SharePoint"", ""Microsoft Dynamics"", ...","[""remote"", ""in_house"", ""mixed""]","[""customer_service"", ""marketing_sales"", ""proce...","[""assertive_communication"", ""teamwork"", ""probl...",food_and_beverages

In [49]:
df_companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213 entries, 0 to 212
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   description                      213 non-null    object
 1   thematic_areas                   14 non-null     object
 2   features_culture_organization    18 non-null     object
 3   digital_tools                    72 non-null     object
 4   work_methods                     71 non-null     object
 5   outstanding_knowledge_community  71 non-null     object
 6   soft_skills                      71 non-null     object
 7   key                              213 non-null    object
dtypes: object(8)
memory usage: 13.4+ KB

In [50]:
df_companies.fillna('', inplace=True) #Elimino valores faltantes que no sirven para el analisis

In [51]:
#Separo las columnas con listas en nuevas columnas

df_companies['digital_tools'] = df_companies['digital_tools'].str.replace('[', '').str.replace(']', '').str.replace("'", "")
df_companies['work_methods'] = df_companies['work_methods'].str.replace('[', '').str.replace(']', '').str.replace("'", "")
df_companies['outstanding_knowledge_community'] = df_companies['outstanding_knowledge_community'].str.replace('[', '').str.replace(']', '').str.replace("'", "")
df_companies['soft_skills'] = df_companies['soft_skills'].str.replace('[', '').str.replace(']', '').str.replace("'", "") 
df_companies['features_culture_organization'] = df_companies['features_culture_organization'].str.replace('[', '').str.replace(']', '').str.replace("'", "") 
df_companies['thematic_areas'] = df_companies['thematic_areas'].fillna('')

In [52]:
df_companies

,description,thematic_areas,features_culture_organization,digital_tools,work_methods,outstanding_knowledge_community,soft_skills,key
0,"Autodesk is a design, engineering, and constru...",,,"""AutoCAD"", ""Revit"", ""Inventor"", ""Maya"", ""Cloud...","""remote"", ""in_house"", ""mixed""","""technology"", ""accounting"", ""customer_service""","""problem_solving"", ""teamwork"", ""innovation"", ""...",technology
1,Somos una compañía que agrupa soluciones en se...,,,,,,,services
2,Every company has a mission. What's ours? To e...,,,"""Microsoft Azure"", ""Microsoft 365"", ""Windows"",...","""remote"", ""in_house"", ""mixed""","""marketing_sales"", ""technology"", ""work_methods...","""assertive_communication"", ""teamwork"", ""proble...",technology
3,General Medica de Colombia SA,,,,,,,health
4,McDonalds is an American fast food restaurant ...,,,"""Webex"", ""SharePoint"", ""Microsoft Dynamics"", ""...","""remote"", ""in_house"", ""mixed""","""customer_service"", ""marketing_sales"", ""proces...","""assertive_communication"", ""teamwork"", ""proble...",food_and_beverages
...,...,...,...,...,...,...,...,...
208,"GAMMA pertenece a la Organización Corona, una ...",,,,,,,others
209,General Motors is an American automotive compa...,,,"""CATIA"", ""Siemens NX"", ""LS-DYNA"", ""OnStar"", ""L...","""remote"", ""in_house"", ""mixed""","""education"", ""accounting"", ""work_methods"", ""fi...","""flexibility"", ""adaptability"", ""organization"",...",automotive
210,Casa Editorial El Tiempo es un grupo de medios...,,,,,,,publishing
211,"At IBM, we do more than work. We create. We cr...",,,"""IBM Cloud"", ""Watson"", ""Red Hat"", ""Linux"", ""Ja...","""remote"", ""in_house"", ""mixed""","""technology"", ""education"", ""work_methods""","""assertive_communication"", ""teamwork"", ""proble...",technology
212,Ford Motor Company is a global automobile comp...,,,"""Autodesk"", ""SolidWorks"", ""Route4Me"", ""Fishbowl""","""remote"", ""in_house"", ""mixed""","""processes"", ""management_leadership"", ""marketi...","""assertive_communication"", ""problem_solving"", ...",automotive

In [53]:
df_companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213 entries, 0 to 212
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   description                      213 non-null    object
 1   thematic_areas                   213 non-null    object
 2   features_culture_organization    213 non-null    object
 3   digital_tools                    213 non-null    object
 4   work_methods                     213 non-null    object
 5   outstanding_knowledge_community  213 non-null    object
 6   soft_skills                      213 non-null    object
 7   key                              213 non-null    object
dtypes: object(8)
memory usage: 13.4+ KB

##### Exploracin de las herramientas digitales mas utilizadas

In [54]:
#Frecuencia de las herramientas digitales utilizadas
digital_tools_freq = df_companies['digital_tools'].str.split(', ').explode().value_counts()

print("Frecuencia de las herramientas digitales mas utilizadas:")
print(digital_tools_freq)

Frecuencia de las herramientas digitales mas utilizadas:
digital_tools
                         151
"SAP"                     18
"Salesforce"              16
"Oracle"                  16
"AWS"                      8
                        ...
"redes sociales"           1
"herramientas de PMO"      1
"Google workspace"         1
"python"                   1
"SQL"                      1
Name: count, Length: 212, dtype: int64

##### Analisis de habilidades blandas y conocimientos destacados

In [55]:
#Frecuencia de las habilidades blandas destacadas
soft_skills_freq = df_companies['soft_skills'].str.split(', ').explode().value_counts()

print("Frecuencia de habilidades blandas destacadas:")
print(soft_skills_freq)

Frecuencia de habilidades blandas destacadas:
soft_skills
                             152
"teamwork"                    49
"problem_solving"             37
"leadership"                  33
"assertive_communication"     28
"creativity"                  21
"critical_thinking"           20
"adaptability"                15
"flexibility"                 13
"innovation"                   9
"time_management"              9
"collaboration"                9
"decision_making"              8
"emotional_intelligence"       6
"ease_adaptation"              5
"empathy"                      4
"fast_learning"                4
"communication"                4
"motivation"                   4
"patience"                     4
"focus"                        4
"punctuality"                  4
"assertive_comunication"       3
"cultural_awareness"           3
"work_ethic"                   3
"organization"                 2
"responsability"               2
"persuasion"                   2
"sociable"                     1
"Problem resolution"           1
"Innovation"                   1
"Assertive comunication"       1
"collaborations"               1
"problem-solving"              1
"resilience"                   1
"initiative"                   1
"Integrity"                    1
"social_skills"                1
"cultural_connection"          1
"resilence"                    1
"critical _thinking"           1
Name: count, dtype: int64

In [56]:
#Frecuencia de los conocimientos destacados
knowledge_freq = df_companies['outstanding_knowledge_community'].str.split(', ').explode().value_counts()

print("\nFrecuencia de conocimientos destacados:")
print(knowledge_freq)

Frecuencia de conocimientos destacados:
outstanding_knowledge_community
                           153
"technology"                37
"marketing_sales"           36
"finance"                   34
"accounting"                22
"processes"                 17
"customer_service"          15
"management_leadership"     12
"work_methods"              11
"education"                  9
"economy"                    5
"economics"                  2
"customer_services"          1
"mangement_leadership"       1
"tecnology"                  1
Name: count, dtype: int64

## CONCLUSIONES 

### Herramientas digitales mas utilizadas:
##### • Ofrecer cursos de capacitacion especificos para las herramientas digitales mas utilizadas, con contenido adaptado a diferentes niveles de habilidad y experiencia.

### Habilidades blandas destacas:
##### • Crear espacios en linea donde los usuarios puedan compartir experiencias y consejos.

### Conocimientos destacados:
##### • Crear espacios de aprendizaje interactivo, con la participacion de una persona con experiencia para poder recomendar y poner en practica estos recursos.

### Feedbacks:
##### • Realizar encuestas de satisfaccion para el cliente/usuario sobre la experiencia dentro de la app para realizar mejoras continuas.

# -

# -

# -

In [195]:
df_users = pd.read_csv('C:/Users/Valen/Desktop/TalentPitch/Prueba BI - Data Analyst/t_users.csv', encoding='utf-8') #Carga de  los datos

In [196]:
df_users.head()

,user_id,about,position,career,updated_at,facebook,instagram,linkedin,website,want_arrive,want_to_be,want_to_work,my_languages,desired_role,my_personality,benefits_in_companies,name,type
0,34491,"Soy una Persona analítica, objetiva, con excel...",NaN,Derecho,2023-09-01 12:10:20,NaN,Juandavidsima,NaN,NaN,"Ser una persona respetada, por las buenas labo...",entrepreneur,"[""https://www.segurossura.com.co/paginas/defau...",NaN,NaN,NaN,"[""bonuses"", ""study_opportunities"", ""flexible_s...","{""es"": ""Politica""}",my_knowledge
1,170899,NaN,Psicóloga,Maestria en MACC,2023-09-01 13:21:24,NaN,NaN,NaN,NaN,NaN,first_job,NaN,"[[""EN"", ""intermediate"", null]]",NaN,NaN,"[""formation""]","{""es"": ""Javascript""}",digital_tools
2,56307,NaN,NaN,NaN,2023-09-01 12:40:14,NaN,NaN,NaN,NaN,NaN,employment,NaN,NaN,NaN,NaN,NaN,"{""es"": ""procesos""}",my_knowledge
3,1968597,NaN,Auxiliar administrativa- Costos,Contaduría,2023-09-19 07:59:45,NaN,NaN,NaN,https://www.linkedin.com/in/claudia-alejandra-...,NaN,employment,"[""Talentpitch""]","[[""ES"", ""advanced"", null]]",CONTABILIDAD,NaN,"[""flexible_schedules"", ""laboral_training"", ""fo...","{""es"": ""Contabilidad""}",my_knowledge
4,1958883,NaN,Desempleado,NaN,2023-09-01 13:26:44,NaN,NaN,NaN,NaN,NaN,employment,NaN,"[[""EN"", ""intermediate""]]",NaN,NaN,NaN,"{""es"": ""Iso""}",my_knowledge

In [197]:
df_users.isnull().sum()

user_id                    0
about                    450
position                 292
career                   103
updated_at                 0
facebook                 818
instagram                851
linkedin                 659
website                  844
want_arrive              848
want_to_be                44
want_to_work             383
my_languages             181
desired_role             763
my_personality           983
benefits_in_companies    403
name                       0
type                       0
dtype: int64

In [198]:
df_users.fillna('', inplace=True) #Elimino valores faltantes que no sirven para el analisis

In [199]:
df_users.isnull().sum()

user_id                  0
about                    0
position                 0
career                   0
updated_at               0
facebook                 0
instagram                0
linkedin                 0
website                  0
want_arrive              0
want_to_be               0
want_to_work             0
my_languages             0
desired_role             0
my_personality           0
benefits_in_companies    0
name                     0
type                     0
dtype: int64

In [200]:
df_users.head()

,user_id,about,position,career,updated_at,facebook,instagram,linkedin,website,want_arrive,want_to_be,want_to_work,my_languages,desired_role,my_personality,benefits_in_companies,name,type
0,34491,"Soy una Persona analítica, objetiva, con excel...",,Derecho,2023-09-01 12:10:20,,Juandavidsima,,,"Ser una persona respetada, por las buenas labo...",entrepreneur,"[""https://www.segurossura.com.co/paginas/defau...",,,,"[""bonuses"", ""study_opportunities"", ""flexible_s...","{""es"": ""Politica""}",my_knowledge
1,170899,,Psicóloga,Maestria en MACC,2023-09-01 13:21:24,,,,,,first_job,,"[[""EN"", ""intermediate"", null]]",,,"[""formation""]","{""es"": ""Javascript""}",digital_tools
2,56307,,,,2023-09-01 12:40:14,,,,,,employment,,,,,,"{""es"": ""procesos""}",my_knowledge
3,1968597,,Auxiliar administrativa- Costos,Contaduría,2023-09-19 07:59:45,,,,https://www.linkedin.com/in/claudia-alejandra-...,,employment,"[""Talentpitch""]","[[""ES"", ""advanced"", null]]",CONTABILIDAD,,"[""flexible_schedules"", ""laboral_training"", ""fo...","{""es"": ""Contabilidad""}",my_knowledge
4,1958883,,Desempleado,,2023-09-01 13:26:44,,,,,,employment,,"[[""EN"", ""intermediate""]]",,,,"{""es"": ""Iso""}",my_knowledge

In [201]:
#Convierto la columna updated_at al formato de fecha y extraigo 
df_users['updated_at'] = pd.to_datetime(df_users['updated_at'])
df_users['updated_at'] = df_users['updated_at'].dt.date

In [202]:
df_users.head()

,user_id,about,position,career,updated_at,facebook,instagram,linkedin,website,want_arrive,want_to_be,want_to_work,my_languages,desired_role,my_personality,benefits_in_companies,name,type
0,34491,"Soy una Persona analítica, objetiva, con excel...",,Derecho,2023-09-01,,Juandavidsima,,,"Ser una persona respetada, por las buenas labo...",entrepreneur,"[""https://www.segurossura.com.co/paginas/defau...",,,,"[""bonuses"", ""study_opportunities"", ""flexible_s...","{""es"": ""Politica""}",my_knowledge
1,170899,,Psicóloga,Maestria en MACC,2023-09-01,,,,,,first_job,,"[[""EN"", ""intermediate"", null]]",,,"[""formation""]","{""es"": ""Javascript""}",digital_tools
2,56307,,,,2023-09-01,,,,,,employment,,,,,,"{""es"": ""procesos""}",my_knowledge
3,1968597,,Auxiliar administrativa- Costos,Contaduría,2023-09-19,,,,https://www.linkedin.com/in/claudia-alejandra-...,,employment,"[""Talentpitch""]","[[""ES"", ""advanced"", null]]",CONTABILIDAD,,"[""flexible_schedules"", ""laboral_training"", ""fo...","{""es"": ""Contabilidad""}",my_knowledge
4,1958883,,Desempleado,,2023-09-01,,,,,,employment,,"[[""EN"", ""intermediate""]]",,,,"{""es"": ""Iso""}",my_knowledge

In [203]:
#Separo las columnas con listas en nuevas columnas

df_users['want_to_work'] = df_users['want_to_work'].str.replace('[', '').str.replace(']', '').str.replace("'", "")
df_users['benefits_in_companies'] = df_users['benefits_in_companies'].str.replace('[', '').str.replace(']', '').str.replace("'", "")

In [204]:
#Reemplazo guiones bajos con espacios en blanco 
df_users['want_to_be'] = df_users['want_to_be'].str.replace('_', ' ')
df_users['type'] = df_users['type'].str.replace('_', ' ')

In [205]:
#Extraigo el nombre en español de un objeto tipop json
def extract_name(json_str):
    try:
        name_dict = json.loads(json_str)
        return name_dict.get('es')
    except (json.JSONDecodeError, TypeError):
        return None

#Aplicar la funcion para extraer el nombre en español
df_users['name'] = df_users['name'].apply(extract_name)

In [207]:
df_users.head(5)

,user_id,about,position,career,updated_at,facebook,instagram,linkedin,website,want_arrive,want_to_be,want_to_work,my_languages,desired_role,my_personality,benefits_in_companies,name,type
0,34491,"Soy una Persona analítica, objetiva, con excel...",,Derecho,2023-09-01,,Juandavidsima,,,"Ser una persona respetada, por las buenas labo...",entrepreneur,"""https://www.segurossura.com.co/paginas/defaul...",,,,"""bonuses"", ""study_opportunities"", ""flexible_sc...",Politica,my knowledge
1,170899,,Psicóloga,Maestria en MACC,2023-09-01,,,,,,first job,,"[[""EN"", ""intermediate"", null]]",,,"""formation""",Javascript,digital tools
2,56307,,,,2023-09-01,,,,,,employment,,,,,,procesos,my knowledge
3,1968597,,Auxiliar administrativa- Costos,Contaduría,2023-09-19,,,,https://www.linkedin.com/in/claudia-alejandra-...,,employment,"""Talentpitch""","[[""ES"", ""advanced"", null]]",CONTABILIDAD,,"""flexible_schedules"", ""laboral_training"", ""for...",Contabilidad,my knowledge
4,1958883,,Desempleado,,2023-09-01,,,,,,employment,,"[[""EN"", ""intermediate""]]",,,,Iso,my knowledge

#### Destacar beneficios laborales atractivos

In [210]:
#Frecuencia de los beneficios laborales atractivos
benefits_freq = df_users['benefits_in_companies'].str.split(', ').explode().value_counts()

print("\nFrecuencia de beneficios laborales:")
print(benefits_freq)

Frecuencia de beneficios laborales:
benefits_in_companies
"study_opportunities"      450
                           420
"flexible_schedules"       354
"laboral_training"         311
"formation"                258
"bonuses"                  226
"scholarships"             198
"home_office"              173
"personal_recognition"     152
"salary_increase"          143
"prepaid_medicine"         119
"distraction_spaces"       114
"free_time"                102
"travels"                   74
"flexible_schedule"         66
"agreements"                65
"events"                    40
"parties_for_employees"     34
"pet_care"                  18
"child_care"                 9
"others"                     3
Name: count, dtype: int64

#### Se observa que las oportunidades de estudio son las mas frecuentes, pero el "home_office" puede mejorar la flexibilidad laboral y las oportunidades de estudio al permitir trabajar desde casa, ya que los empleados pueden gestionar sus horarios de manera mas eficiente y reduce el tiempo perdido en desplazamientos hacia y desde el lugar de trabajo.

### Aspiraciones o roles deseados por el usuario

In [215]:
#Frecuencia de aspiraciones/roles deseados
want_freq = df_users['want_to_be'].str.split(', ').explode().value_counts()

print("\nFrecuencia roles/aspiraciones:")
print(want_freq)

Frecuencia roles/aspiraciones:
want_to_be
employment      681
first job       121
freelancer       77
entrepreneur     53
                 44
practice         24
Name: count, dtype: int64

##### Al observar los datos proporcionados, los roles de "empleo" y "primer empleo" son los más destacados entre los usuarios que postulan en la plataforma,este hallazgo sugiere una oportunidad para enfocarse en ayudar a los usuarios a alcanzar estos objetivos profesionales especificos.

####  Utilizar las columnas "about", "career" y "my_personality" para desarrollar un algoritmo de recomendacion que sugiera contenido, recursos o servicios personalizados a los usuarios al momento de crear sus perfiles en la plataforma, utilizando tecnicas de procesamiento de lenguaje natural para extraer informacion relevante que sirvan como base para las recomendaciones a cada usuario.

# -

# -

In [225]:
df_companies.to_csv('df_companies_final.csv', index=False)
df_users.to_csv('df_user_final.csv', index=False)